Getting run and check scripts to use subject lists

diff --git a/check_ccf_struct b/check_ccf_struct
--- a/check_ccf_struct
+++ b/check_ccf_struct
@@ -42,6 +42,10 @@ get_options()
 				g_run_type="SANDBOX"
 				index=$(( index + 1 ))
 				;;
+			--subject-list=*)
+				g_subject_list_file=${argument/*=/""}
+				index=$(( index + 1 ))
+				;;
 			*)
 				echo "Unrecognized option: ${argument}"
 				exit 1
@@ -61,31 +65,93 @@ get_options()
 		echo "ERROR: run type must be CONTAINER or SANDBOX"
 		exit 1
 	fi
+
+	if [ -n "${g_subject_list_file}" ]; then
+		echo "INFO: running processing for subjects listed in file: ${g_subject_list_file}"
+	else
+		echo "ERROR: --subject-list=<subject-list-filename> must be specified"
+		exit 1
+	fi
 }
 
 main()
 {
-	get_options "$@"
-
+	local line
 	local run_cmd
-	run_cmd=""
+	local where_data_are_on_my_system
+	local where_data_must_be_in_container
 
-	if [ "${g_run_type}" = "CONTAINER" ]; then
-		run_cmd+="singularity run  -B ${HOME}/data:/data --app StructuralPreprocessingCheckData HCPprocessPipelines.img"
-	elif [ "${g_run_type}" = "SANDBOX" ]; then
-		run_cmd+="singularity exec -B ${HOME}/data:/data HCPprocessPipelinesSandbox/ /pipeline_tools/hcp_pipelines_run_utils/StructuralPreprocessing/StructuralPreprocessing.CHECK"
-	else
-		echo "ERROR: Unrecognized run type: ${g_run_type}"
-		exit 1
-	fi
+	get_options "$@"
+	
+	while read -r line; do
+		# remove comments - anything after a #
+		line=${line%%\#*}
+		
+		# trim leading and trailing whitespace
+		line=$(echo ${line} | xargs)
+		
+		if [ -z "${line}" ]; then
+			continue
+		fi
+			
+		# break into subject_id, pos_fieldmap, and neg_fieldmap
+		subject_id=${line%%:*}			# subject_id is everything before the first :
+		line=${line#${subject_id}:} 	# strip subject_id and : from the front of line
+		
+		pos_fieldmap=${line%%:*}		# pos_fieldmap is everything before the first :
+		line=${line#${pos_fieldmap}:}	# strip pos_fieldmap and : from the front of line
+		
+		neg_fieldmap=${line}			# neg_fieldmap is everything that is left
 
-	run_cmd+=" --working-dir=/data/mystudy"
-	run_cmd+=" --subject=HCA6005242"
-	run_cmd+=" --classifier=V1_MR"
+		echo ""
+		echo "-- Checking completeness for subject: ${subject_id}:${pos_fieldmap}:${neg_fieldmap} --"
+		echo ""
 
-	echo "run_cmd: ${run_cmd}"
+		run_cmd=""
 
-	time ${run_cmd}
+		# Base Singularity command
+		if [ "${g_run_type}" = "CONTAINER" ]; then
+			run_cmd+="singularity run"
+		elif [ "${g_run_type}" = "SANDBOX" ]; then
+			run_cmd+="singularity exec"
+		else
+			echo "ERROR: Unrecognized run type: ${g_run_type}"
+			exit 1
+		fi
+
+		# Bind your data directory
+		# Needs to show up as the /data directory in the Container/Sandbox
+		where_data_are_on_my_system="${HOME}/data"
+		where_data_must_be_in_container="/data"
+
+		run_cmd+=" -B ${where_data_are_on_my_system}:${where_data_must_be_in_container}"
+
+		# Specify command or script to run
+		if [ "${g_run_type}" = "CONTAINER" ]; then
+			# application in the container to run
+			run_cmd+=" --app StructuralPreprocessingCheckData"
+			# container image file
+			run_cmd+=" HCPprocessPipelines.img"
+		elif [ "${g_run_type}" = "SANDBOX" ]; then
+			# sandbox directory 
+			run_cmd+=" HCPprocessPipelinesSandbox/"
+			# full path to script within sandbox to execute
+			run_cmd+=" /pipeline_tools/HCPpipelinesRunUtils/StructuralPreprocessing/StructuralPreprocessing.CHECK"
+		else
+			echo "ERROR: Unrecognized run type: ${g_run_type}"
+			exit 1
+		fi
+
+		# Add command line parameters for command/script to run
+		run_cmd+=" --working-dir=/data/mystudy"
+		run_cmd+=" --subject=HCA6005242"
+		run_cmd+=" --classifier=V1_MR"
+
+		echo "run_cmd: ${run_cmd}"
+		
+		time ${run_cmd}
+
+	done < "${g_subject_list_file}"
 }
 
 # Invoke the main function to get things started
diff --git a/run_hcp_struct b/run_hcp_struct
--- a/run_hcp_struct
+++ b/run_hcp_struct
@@ -63,7 +63,8 @@ get_options()
 
 	# initialize global output variables
 	unset g_run_type
-
+	unset g_subject_list_file
+	
 	# parse arguments
 	local num_args=${#arguments[@]}
 	local argument
@@ -86,6 +87,10 @@ get_options()
 				g_run_type="SANDBOX"
 				index=$(( index + 1 ))
 				;;
+			--subject-list=*)
+				g_subject_list_file=${argument/*=/""}
+				index=$(( index + 1 ))
+				;;
 			*)
 				echo "Unrecognized option: ${argument}"
 				exit 1
@@ -105,105 +110,130 @@ get_options()
 		echo "ERROR: run type must be CONTAINER or SANDBOX"
 		exit 1
 	fi
+
+	if [ -n "${g_subject_list_file}" ]; then
+		echo "INFO: running processing for subjects listed in file: ${g_subject_list_file}"
+	else
+		echo "ERROR: --subject-list=<subject-list-filename> must be specified"
+		exit 1
+	fi
 }
 
 main()
 {
-	get_options "$@"
-
+	local line
 	local run_cmd
-	run_cmd=""
-
-	# Base Singularity command
-	if [ "${g_run_type}" = "CONTAINER" ]; then
-		run_cmd+="singularity run"
-	elif [ "${g_run_type}" = "SANDBOX" ]; then
-		run_cmd+="sudo singularity exec"
-	else
-		echo "ERROR: Unrecognized run type: ${g_run_type}"
-	fi
-
-	# Bind your data directory
-	# Needs to show up as the /data directory in the Container/Sandbox
-
+	local subject_id
 	local where_data_are_on_my_system
 	local where_data_must_be_in_container
-	
-	where_data_are_on_my_system="${HOME}/data"
-	where_data_must_be_in_container="/data"
-
-	run_cmd+=" -B ${where_data_are_on_my_system}:${where_data_must_be_in_container}"
-
-	# Bind gradient coefficients files directory
-	# Needs to show up as the /export/HCP/gradient_coefficient_files directory in the Container/Sandbox
-
 	local where_gc_files_are_on_my_system
 	local where_gc_files_must_be_in_container
-	
-	where_gc_files_are_on_my_system="${HOME}/projects/HCPpipelinesPrereqs/gradient_coefficients_files"
-	where_gc_files_must_be_in_container="/export/HCP/gradient_coefficient_files"
-	
-	run_cmd+=" -B ${where_gc_files_are_on_my_system}:${where_gc_files_must_be_in_container}"
-
-	# Bind folder with FreeSurfer License
-	# Needs to show up as the /export/freesurfer_license directory in the Container/Sandbox
-	# Must contain a file named 'license.txt'
-
 	local where_license_file_is_on_my_system
 	local where_license_file_must_be_in_container
 
-	where_license_file_is_on_my_system="${HOME}/projects/HCPpipelinesPrereqs/FreeSurferLicense"
-	where_license_file_must_be_in_container="/export/freesurfer_license"
+	get_options "$@"
+
+	while read -r line; do
+		# remove comments - anything after a #
+		line=${line%%\#*}
+
+		# trim leading and trailing whitespace
+		line=$(echo ${line} | xargs)
+
+		if [ -z "${line}" ]; then
+			continue
+		fi
+
+		subject_id=${line}
+
+		echo ""
+		echo "-- Running processing for subject: ${subject_id} --"
+		echo ""
+		
+		run_cmd=""
+
+		# Base Singularity command
+		if [ "${g_run_type}" = "CONTAINER" ]; then
+			run_cmd+="singularity run"
+		elif [ "${g_run_type}" = "SANDBOX" ]; then
+			run_cmd+="sudo singularity exec"
+		else
+			echo "ERROR: Unrecognized run type: ${g_run_type}"
+			exit 1
+		fi
+
+		# Bind your data directory
+		# Needs to show up as the /data directory in the Container/Sandbox
+		where_data_are_on_my_system="${HOME}/data"
+		where_data_must_be_in_container="/data"
+
+		run_cmd+=" -B ${where_data_are_on_my_system}:${where_data_must_be_in_container}"
+
+		# Bind gradient coefficients files directory
+		# Needs to show up as the /export/HCP/gradient_coefficient_files directory in the Container/Sandbox
+		where_gc_files_are_on_my_system="${HOME}/projects/HCPpipelinesPrereqs/gradient_coefficients_files"
+		where_gc_files_must_be_in_container="/export/HCP/gradient_coefficient_files"
 	
-	run_cmd+=" -B ${where_license_file_is_on_my_system}:${where_license_file_must_be_in_container}"
+		run_cmd+=" -B ${where_gc_files_are_on_my_system}:${where_gc_files_must_be_in_container}"
 
-	# Specify command or script to run
-	if [ "${g_run_type}" = "CONTAINER" ]; then
-		# application in the container to run
-		run_cmd+=" --app StructuralPreprocessing"
-		# container image file
-		run_cmd+=" HCPprocessPipelines.img"
-	elif [ "${g_run_type}" = "SANDBOX" ]; then
-		# sandbox directory
-		run_cmd+=" HCPprocessPipelinesSandbox/"
-		# full path to script within sandbox to execute
-		run_cmd+=" /pipeline_tools/hcp_pipelines_run_utils/StructuralPreprocessing/StructuralPreprocessing.SINGULARITY_PROCESS"
-	else
-		echo "ERROR: Unrecognized run type: ${g_run_type}"
-	fi
-
-	# Add command line parameters for command/script to run
-	run_cmd+=" --working-dir=/data/mystudy"	# Note: this path is from within the container
-	run_cmd+=" --subject=100307"
-	run_cmd+=" --classifier=3T"
-	run_cmd+=" --brainsize=150"
-
-	run_cmd+=" --first-t1w-directory-name=T1w_MPR1"
-	run_cmd+=" --first-t1w-file-name=100307_3T_T1w_MPR1.nii.gz"
-
-	run_cmd+=" --first-t2w-directory-name=T2w_SPC1"
-	run_cmd+=" --first-t2w-file-name=100307_3T_T2w_SPC1.nii.gz"
-
-	run_cmd+=" --t1template=MNI152_T1_0.7mm.nii.gz"
-	run_cmd+=" --t1templatebrain=MNI152_T1_0.7mm_brain.nii.gz"
-	run_cmd+=" --t1template2mm=MNI152_T1_2mm.nii.gz"
-
-	run_cmd+=" --t2template=MNI152_T2_0.7mm.nii.gz"
-	run_cmd+=" --t2templatebrain=MNI152_T2_0.7mm_brain.nii.gz"
-	run_cmd+=" --t2template2mm=MNI152_T2_2mm.nii.gz"
-
-	run_cmd+=" --templatemask=MNI152_T1_0.7mm_brain_mask.nii.gz"
-	run_cmd+=" --template2mmmask=MNI152_T1_2mm_brain_mask_dil.nii.gz"
-
-	run_cmd+=" --fnirtconfig=T1_2_MNI152_2mm.cnf"
-	run_cmd+=" --gdcoeffs=coeff_SC72C_Skyra.grad"
-	run_cmd+=" --topupconfig=b02b0.cnf"
+		# Bind folder with FreeSurfer License
+		# Needs to show up as the /export/freesurfer_license directory in the Container/Sandbox
+		# Must contain a file named 'license.txt'
+		where_license_file_is_on_my_system="${HOME}/projects/HCPpipelinesPrereqs/FreeSurferLicense"
+		where_license_file_must_be_in_container="/export/freesurfer_license"
 	
-	run_cmd+=" --fieldmap-type=SiemensGradientEcho"
+		run_cmd+=" -B ${where_license_file_is_on_my_system}:${where_license_file_must_be_in_container}"
 
-	echo "run_cmd: ${run_cmd}"
+		# Specify command or script to run
+		if [ "${g_run_type}" = "CONTAINER" ]; then
+			# application in the container to run
+			run_cmd+=" --app StructuralPreprocessing"
+			# container image file
+			run_cmd+=" HCPprocessPipelines.img"
+		elif [ "${g_run_type}" = "SANDBOX" ]; then
+			# sandbox directory
+			run_cmd+=" HCPprocessPipelinesSandbox/"
+			# full path to script within sandbox to execute
+			run_cmd+=" /pipeline_tools/HCPpipelinesRunUtils/StructuralPreprocessing/StructuralPreprocessing.SINGULARITY_PROCESS"
+		else
+			echo "ERROR: Unrecognized run type: ${g_run_type}"
+			exit 1
+		fi
 
-	time ${run_cmd}
+		# Add command line parameters for command/script to run
+		run_cmd+=" --working-dir=/data/mystudy"	# Note: this path is from within the container
+		run_cmd+=" --subject=${subject_id}"
+		run_cmd+=" --classifier=3T"
+		run_cmd+=" --brainsize=150"
+
+		run_cmd+=" --first-t1w-directory-name=T1w_MPR1"
+		run_cmd+=" --first-t1w-file-name=${subject_id}_3T_T1w_MPR1.nii.gz"
+
+		run_cmd+=" --first-t2w-directory-name=T2w_SPC1"
+		run_cmd+=" --first-t2w-file-name=${subject_id}_3T_T2w_SPC1.nii.gz"
+
+		run_cmd+=" --t1template=MNI152_T1_0.7mm.nii.gz"
+		run_cmd+=" --t1templatebrain=MNI152_T1_0.7mm_brain.nii.gz"
+		run_cmd+=" --t1template2mm=MNI152_T1_2mm.nii.gz"
+
+		run_cmd+=" --t2template=MNI152_T2_0.7mm.nii.gz"
+		run_cmd+=" --t2templatebrain=MNI152_T2_0.7mm_brain.nii.gz"
+		run_cmd+=" --t2template2mm=MNI152_T2_2mm.nii.gz"
+
+		run_cmd+=" --templatemask=MNI152_T1_0.7mm_brain_mask.nii.gz"
+		run_cmd+=" --template2mmmask=MNI152_T1_2mm_brain_mask_dil.nii.gz"
+		
+		run_cmd+=" --fnirtconfig=T1_2_MNI152_2mm.cnf"
+		run_cmd+=" --gdcoeffs=coeff_SC72C_Skyra.grad"
+		run_cmd+=" --topupconfig=b02b0.cnf"
+	
+		run_cmd+=" --fieldmap-type=SiemensGradientEcho"
+
+		echo "run_cmd: ${run_cmd}"
+
+		time ${run_cmd}
+
+	done < "${g_subject_list_file}"
 }
 			
 # Invoke the main function to get things started
