* changed name of Singularity image file to use .simg extension * changed recipe to use HCPpipelines with latest FreeSurfer 6 changes * removed tess1mm FreeSurfer 6 customization as it is no longer needed * created single convenience script for building container or sandbox   from various sources * created single convenience script to run CCF Structural Preprocessing   related apps in the container or sandbox * created single convenience script to enter container or sandbox for   testing

diff --git a/run_hcp_struct b/run_hcp_struct
--- a/run_hcp_struct
+++ b/run_hcp_struct
@@ -1,69 +1,157 @@
 #!/bin/bash
 
-# This utility script demonstrates how to test run the Structural Preprocessing
-# on an HCP-YA subject either from within the HCPprocessPipelines.img Singularity
-# container or from within the HCPprocessPipelinesSandbox.
-#
-# Directories that are bound from your local system to the container.
-# -------------------------------------------------------------------
-#
-# If the assumptions listed below are not true in your environment, you may need
-# to modify this script to run properly.
-#
-#   Data Directory
-#   --------------
-# 
-#   This script assumes that you have a directory named:
-#
-#     ${HOME}/data/mystudy
-#
-#   The 'mystudy' directory is assumed to be in the standard HCP Pipelines format,
-#   i.e. with subdirectories for each subject, with those subdirectories named with
-#   the subject's ID.
-#
-#   The ${HOME}/data directory is mounted/bound and available within the HCPprocessPipelines
-#   container or the HCPprocessPipelinesSandbox as the /data directory. Thus the value
-#   specified for the --working-dir= parameter when running the processing script is
-#   '/data/mystudy'.
-#
-#   Gradient Coefficient Files Directory
-#   ------------------------------------
-#
-#   This script assumes that you have a directory named:
-#
-#     ${HOME}/projects/HCPpipelinesPrereqs/gradient_coefficients_files
-#
-#   That 'gradient_coefficients_files' directory is assumed to contain the proprietary
-#   gradient distortion coefficients files for any scanners used in collecting your
-#   image data files.
-#
-#   The ${HOME}/projects/.../gradient_coefficients_files directory is mounted/bound
-#   within the HCPprocessPipelines container or the HCPprocessPipelinesSandbox as the
-#   /export/HCP/gradient_coefficient_files directory. This is where the gradient
-#   coefficients files must be found within the container.
-#
-#   FreeSurfer Licence File Directory
-#   ---------------------------------
-#
-#   This script assumes that you have a directory named:
-#
-#     ${HOME}/projects/HCPpipelinesPrereqs/FreeSurferLicense
-#
-#   The 'FreeSurferLicense' directory is assumed to contain your FreeSurfer license
-#   in a file named: 'license.txt'
-#
-#   The ${HOME}/projects/.../FreeSurferLicense directory is mounted/bound
-#   within the HCPprocessPipelines container or the HCPprocessPipelinesSandbox as the
-#   /export/freesurfer_license directory. This is where the 'license.txt' file must
-#   be found within the container.
+SCRIPT_NAME=$(basename "${0}")
+DEFAULT_STUDY_DIR="${HOME}/data/mystudy"
+DEFAULT_GRADIENT_COEFFS_DIR="${HOME}/projects/HCPpipelinesPrereqs/gradient_coefficients_files"
+DEFAULT_FREESURFER_LICENSE_DIR="${HOME}/projects/HCPpipelinesPrereqs/FreeSurferLicense"
+
+usage()
+{
+	cat <<EOF
+
+${SCRIPT_NAME}: 
+
+  This script demonstrates how to run Structural Preprocessing related applications 
+  available within the HCPprocessPipelines.simg Singularity container or within the 
+  corresponding HCPprocessPipelinesSandbox on HCP-YA subjects.
+
+Usage: ${SCRIPT_NAME} PARAMETER ...
+
+PARAMETERS are: [ ] = optional; < > = user supplied value
+
+  [--help] : show this usage information and exit
+
+  Path to study directory
+  -----------------------
+
+  [--study-dir=<path-to-study-directory>]
+
+    The specified path will be bound (i.e. mounted) from your system
+    to a known location (/study) in the container or sandbox. This is 
+    where the study data must be found within the container or sandbox.
+
+    It is assumed that your study directory contains subdirectories that 
+    correspond to your subject IDs.
+
+    If you do not specify a study directory, the study directory will 
+    default to: ${DEFAULT_STUDY_DIR}.
+
+  Path to gradient coefficients files
+  -----------------------------------
+
+  [--gradient-coeffs-dir=<path-to-gradient-coefficients-directory>]
+
+    The specified path will be bound (i.e. mounted) from your system
+    to a known location (/export/HCP/gradient_coefficient_files) in the
+    container or sandbox. This is where the gradient coefficients
+    files must be found within the container or sandbox.
+
+    This gradient coefficients files directory must contain the
+    proprietary gradient coefficients files for any scanners used in 
+    collecting your image data files.
+
+    If you do not specify a gradient coefficients files directory, it will
+    default to: ${DEFAULT_GRADIENT_COEFFS_DIR}.  
+
+    NOTE: The path to the gradient coefficients files is only necessary
+    for actual processing of data. If you are running a completion
+    check, you can allow this to take its default value even if that
+    value is incorrect.  
+
+  Path to FreeSurfer license file
+  -------------------------------
+
+  [--freesurfer-license-dir=<path-to-freesurfer-license-directory>]
+
+    The specified path will be bound (i.e. mounted) from your system
+    to a known location (/export/freesurfer_license) in the container
+    or sandbox. This is where the FreeSurfer license file must be
+    found within the container or sandbox.
+
+    If you do not specify a FreeSurfer license directory, it will 
+    default to: ${DEFAULT_FREESURFER_LICENSE_DIR}.
+
+    NOTE: The path to the FreeSurfer license file is only necessary
+    for actual processing of data. If you are running a completion
+    check, you can allow this to take its default value even if that
+    value is incorrect.  
+
+  Specification of environment
+  ----------------------------
+
+    You must specify whether to perform the requested processing
+    in the Singularity Container (HCPprocessPipelines.simg) or 
+    in the Singularity Sandbox (HCPprocessPipelinesSandbox/).
+
+    One of the following options must be specified:
+
+      --env=[CONTAINER|SANDBOX]
+      --container
+      --sandbox
+
+    The value specified for the --env= parameter is not case
+    sensitive, but must be either CONTAINER or SANDBOX. For example, 
+    --env=ConTAiner, --env=SandBox, and --env=sandbox
+    are all valid, but --env=CONTAIN is not valid.
+
+      --container is equivalent to --env=CONTAINER
+
+      --sandbox is equivalent to --env=SANDBOX
+
+    NOTE: To run within the Sandbox, you will need sudo privileges
+    on the machine on which you are running. When commands are run
+    with sudo, you may be prompted for your password to validate 
+    your sudo privileges. 
+
+  Subject List File
+  -----------------
+
+    You must specify a file containing a list of subject information lines. 
+
+    Each line in the subject file must contain the following information:
+
+      <subject-id>
+
+    Anything after a # on a line is considered a comment. To comment out a subject
+    information line, simply insert a # as the very first character on the line
+
+    Each subject information line will be parsed and the container or sandbox will 
+    be used to run the specified processing for the specified subject.
+
+  Processing
+  ----------
+
+    This script will run the actual Structural Preprocessing for the specified 
+    subjects. It is not implemented to run the completion check for Structural 
+    Preprocessing.
+
+EOF
+}
+
+abort()
+{
+	local error_msg
+	error_msg="${1}"
+
+	echo ""
+	usage
+	echo "--------------------------------------------------"
+	echo "ERROR: ${error_msg}"
+	echo "--------------------------------------------------"
+	echo ""
+	exit 1
+}
 
 get_options()
 {
 	local arguments=($@)
 
 	# initialize global output variables
-	unset g_run_type
 	unset g_subject_list_file
+	g_study_dir="${DEFAULT_STUDY_DIR}"
+	g_gradient_coeffs_dir="${DEFAULT_GRADIENT_COEFFS_DIR}"
+	g_freesurfer_license_dir="${DEFAULT_FREESURFER_LICENSE_DIR}"
+	unset g_env
 	
 	# parse arguments
 	local num_args=${#arguments[@]}
@@ -74,9 +162,25 @@ get_options()
 		argument=${arguments[index]}
 
 		case ${argument} in
-			--run-type=*)
-				g_run_type=${argument/*=/""}
-				g_run_type=$(echo ${g_run_type} | tr '[:lower:]' '[:upper:]')
+			--help)
+				usage
+				exit 1
+				;;
+			--study-dir=*)
+				g_study_dir=${argument/*=/""}
+				index=$(( index + 1 ))
+				;;
+			--gradient-coeffs_dir=*)
+				g_gradient_coeffs_dir=${argument/*=/""}
+				index=$(( index + 1 ))
+				;;
+			--freesurfer-license-dir=*)
+				g_freesurfer_license_dir=${argument/*=/""}
+				index=$(( index + 1 ))
+				;;
+			--env=*)
+				g_env=${argument/*=/""}
+				g_env=$(echo ${g_run_type} | tr '[:lower:]' '[:upper:]')
 				index=$(( index + 1 ))
 				;;
 			--container)
@@ -101,21 +205,38 @@ get_options()
 
 	# check parameters
 
-	if [ -z "${g_run_type}" ]; then
-		echo "ERROR: run type (--run-type=[CONTAINER|SANDBOX], --container, or --sandbox) required"
-		exit 1
+	if [ -n "${g_study_dir}" ]; then
+		echo "INFO: study directory: ${g_study_dir}"
+	else
+		abort "--study-dir=<study-directory> must be specified"
 	fi
 
-	if [ "${g_run_type}" != "CONTAINER" -a "${g_run_type}" != "SANDBOX" ]; then 
-		echo "ERROR: run type must be CONTAINER or SANDBOX"
-		exit 1
+	if [ -n "${g_gradient_coeffs_dir}" ]; then
+		echo "INFO: gradient coefficients directory: ${g_gradient_coeffs_dir}"
+	else
+		abort "--gradient-coeffs-dir=<gradient-coeffs-directory> must be specified"
+	fi
+
+	if [ -n "${g_freesurfer_license_dir}" ]; then
+		echo "INFO: FreeSurfer license directory: ${g_freesurfer_license_dir}"
+	else
+		abort "--freesurfer-license-dir=<freesurfer-license-directory> must be specified"
+	fi
+	
+	if [ -z "${g_env}" ]; then
+		abort "run type (--env=[CONTAINER|SANDBOX], --container, or --sandbox) required"
+	fi
+
+	if [ "${g_env}" != "CONTAINER" -a "${g_env}" != "SANDBOX" ]; then 
+		abort "environment must be CONTAINER or SANDBOX"
+	else
+		echo "INFO: Environment: ${g_env}"
 	fi
 
 	if [ -n "${g_subject_list_file}" ]; then
 		echo "INFO: running processing for subjects listed in file: ${g_subject_list_file}"
 	else
-		echo "ERROR: --subject-list=<subject-list-filename> must be specified"
-		exit 1
+		abort "--subject-list=<subject-list-filename> must be specified"
 	fi
 }
 
@@ -124,8 +245,8 @@ main()
 	local line
 	local run_cmd
 	local subject_id
-	local where_data_are_on_my_system
-	local where_data_must_be_in_container
+	local where_study_is_on_my_system
+	local where_study_must_be_in_container
 	local where_gc_files_are_on_my_system
 	local where_gc_files_must_be_in_container
 	local where_license_file_is_on_my_system
@@ -134,6 +255,7 @@ main()
 	get_options "$@"
 
 	while read -r line; do
+		
 		# remove comments - anything after a #
 		line=${line%%\#*}
 
@@ -158,16 +280,15 @@ main()
 		elif [ "${g_run_type}" = "SANDBOX" ]; then
 			run_cmd+="sudo singularity exec"
 		else
-			echo "ERROR: Unrecognized run type: ${g_run_type}"
-			exit 1
+			abort "Unrecognized run type: ${g_run_type}"
 		fi
 
-		# Bind your data directory
-		# Needs to show up as the /data directory in the Container/Sandbox
-		where_data_are_on_my_system="${HOME}/data"
-		where_data_must_be_in_container="/data"
+		# Bind your study directory
+		# Needs to show up as the /study directory in the Container/Sandbox
+		where_study_is_on_my_system="${g_study_dir}"
+		where_study_must_be_in_container="/study"
 
-		run_cmd+=" -B ${where_data_are_on_my_system}:${where_data_must_be_in_container}"
+		run_cmd+=" -B ${where_study_is_on_my_system}:${where_study_must_be_in_container}"
 
 		# Bind gradient coefficients files directory
 		# Needs to show up as the /export/HCP/gradient_coefficient_files directory in the Container/Sandbox
@@ -185,23 +306,22 @@ main()
 		run_cmd+=" -B ${where_license_file_is_on_my_system}:${where_license_file_must_be_in_container}"
 
 		# Specify command or script to run
-		if [ "${g_run_type}" = "CONTAINER" ]; then
+		if [ "${g_env}" = "CONTAINER" ]; then
 			# application in the container to run
 			run_cmd+=" --app StructuralPreprocessing"
 			# container image file
-			run_cmd+=" HCPprocessPipelines.img"
-		elif [ "${g_run_type}" = "SANDBOX" ]; then
+			run_cmd+=" HCPprocessPipelines.simg"
+		elif [ "${g_env}" = "SANDBOX" ]; then
 			# sandbox directory
 			run_cmd+=" HCPprocessPipelinesSandbox/"
 			# full path to script within sandbox to execute
 			run_cmd+=" /pipeline_tools/HCPpipelinesRunUtils/StructuralPreprocessing/StructuralPreprocessing.SINGULARITY_PROCESS"
 		else
-			echo "ERROR: Unrecognized run type: ${g_run_type}"
-			exit 1
+			abort "Unrecognized run type: ${g_run_type}"
 		fi
 
 		# Add command line parameters for command/script to run
-		run_cmd+=" --working-dir=/data/mystudy"	# Note: this path is from within the container
+		run_cmd+=" --working-dir=/study"	# Note: this path is from within the container
 		run_cmd+=" --subject=${subject_id}"
 		run_cmd+=" --classifier=3T"
 		run_cmd+=" --brainsize=150"
